"""Default settings values for NeuroSyncApp."""

from __future__ import annotations

from copy import deepcopy


DEFAULT_SETTINGS: dict[str, str] = {
    "selected_trace_color": "green",
    "selected_sem_color": "grey",
    "selected_bar_sem_color": "grey",
    "selected_bar_fill_color": "blue",
    "selected_bar_border_color": "black",
    "selected_line_color": "red",
    "selected_temp_line_color": "red",
    "selected_activity_bar_color": "blue",
    "selected_cluster_box_color": "orange",
    "default_onset_line_color": "red",
    "default_sem_color": "grey",
    "default_line_color": "red",
    "default_bar_sem_color": "grey",
    "default_bar_fill_color": "blue",
    "default_bar_border_color": "black",
    "default_trace_color": "green",
    "default_temp_line_color": "red",
    "default_activity_bar_color": "blue",
    "default_temp_sem_color": "orange",
    "default_photometry_line_color": "green",
    "default_cluster_box_color": "orange",
    "default_cluster_box_alpha": "0.2",
    "default_cluster_box_height_modifier": "1",
    "selected_label_color": "red",
    "selected_label_symbol": "*",
    "selected_label_size": "12",
    "selected_y_offset_peak_symbol": "0",
    "selected_peak_count_color": "red",
    "selected_peak_count_size": "12",
    "selected_y_for_peak_count": "10",
    "selected_baseline_multiplier": "",
    "selected_baseline_color": "green",
    "selected_baseline_style": "--",
    "selected_baseline_thickness": "1",
    "selected_photometry_line_color": "black",
    "selected_photometry_line_alpha": "1.0",
    "selected_cluster_box_alpha": "0.2",
    "selected_cluster_box_height_modifier": "1",
    "light_off_time_var": "19:00:00",
    "selected_photometry_line_width": "0.5",
    "selected_horizontal_scale_bar_offset": "10",
    "selected_vertical_scale_bar_offset": "10",
    "selected_scale_bar_color": "black",
    "selected_scale_bar_width": "2",
    "selected_scale_bar_size": "5",
    "selected_temp_mean_line_width": "1",
    "selected_temp_mean_line_color": "red",
    "selected_temp_sem_color": "red",
    "selected_temp_mean_line_alpha": "1.0",
    "selected_temp_sem_line_alpha": "0.1",
    "selected_temp_desired_offset": "0.5",
    "selected_temp_desired_scale": "0.4",
    "selected_temp_y_axis_color": "red",
    "selected_temp_num_ticks": "10",
    "selected_activity_mean_bar_color": "green",
    "selected_activity_mean_bar_alpha": "0.5",
    "selected_activity_desired_offset": "0",
    "selected_activity_desired_scale": "0.3",
    "selected_activity_y_axis_color": "green",
    "selected_activity_num_bins": "",
    "selected_activity_num_ticks": "10",
    "telemetry_folder_path": "",
    "default_data_folder_path": "",
    "number_of_minor_ticks": "0",
    "remove_first_60_minutes_var": True,
    "onset_line_color": "red",
    "onset_line_thickness": "1",
    "onset_line_style": "--",
    "duration_box_placement": "1.0",
    "box_height_factor": "0.2",
    "alpha": "0.2",
    "bar_graph_size": "0.2",
    "selected_column_name": "",
    "selected_time_column": "#time(seconds)",
    "selected_405nm_column": "405nm",
    "selected_465nm_column": "465nm",
}


def get_default_settings() -> dict[str, str]:
    """Return a fresh copy of the project default settings."""
    return deepcopy(DEFAULT_SETTINGS)
